#' describeBatch
#'
#' Generate summary information for a batch of image chips and masks.
#'
#' The goal of this function is to provide a check of a batch of image chips and associated
#' masks generated by a DataLoader instance using defineSegDataSet(). Summary information includes the batch size
#' (batchSize); image chip data type (imageDataType); mask data type (maskDataType); the shape of the batch of images
#' or predictor variables as mini-batch size, number of channels, width pixel count, and height pixel count (imageShape); the mask shape
#' (maskShape); image band means (bndMns); image band standard deviations (bndSDs);
#' count of pixels in each class in the batch (mskCnts); and minimum (minIndex) and maximum (maxIndex) class indices present in the batch.
#'
#' @param dataLoader Instantiated instance of a DataLoader created using torch::dataloader().
#' @param zeroStart TRUE or FALSE. If class indices start at 0, set this to TRUE. If they start at 1,
#' set this to FALSE. Default is FALSE.
#' @param usedDS TRUE or FALSE. If deep supervision is implemented, this must be set to TRUE.
#' Default is FALSE. Whether or not deep supervision was used, only metrics for the masks
#' at the original spatial resolution are returned.
#' @return List object summarizing a batch of image chips and masks.
#' @export
describeBatch <- function(dataLoader, zeroStart=FALSE, usedDS=FALSE){

  batch1 <- dataLoader$.iter()$.next()

  if(usedDS==TRUE){
    imgDims <- batch1$image[1]$shape |> as.character()
    mskDims <- batch1$mask$mask1[1]$shape |> as.character()
    imgDT <- batch1$image[1]$dtype |> as.character()
    mskDT <- batch1$mask$mask1[1]$dtype |> as.character()
  }else{
    imgDims <- batch1$image$shape |> as.character()
    mskDims <- batch1$mask$shape |> as.character()
    imgDT <- batch1$image[1]$dtype |> as.character()
    mskDT <- batch1$mask[1]$dtype |> as.character()
  }

  if(usedDS == TRUE){
    mask <- batch1$mask$mask1
  }else{
    mask <- batch1$mask
  }

  if(zeroStart==TRUE){
    maskFreq <- mask+1
  }else{
    maskFreq <- mask
  }
  freqTble <- torch::torch_bincount(torch::torch_tensor(mask, dtype=torch::torch_long())$flatten())$cpu() |>
    torch::as_array() |>
    as.vector()

  maxIndex <- torch::torch_max(mask)$cpu() |>
    torch::as_array() |>
    as.vector()
  minIndex <- torch::torch_min(mask)$cpu() |>
    torch::as_array() |>
    as.vector()

  bndMns <- torch::torch_mean(batch1$image, dim=c(1,3,4))$cpu() |>
    torch::as_array() |>
    as.vector()

  bndSDs <- torch::torch_std(batch1$image, dim=c(1,3,4))$cpu() |>
    torch::as_array() |>
    as.vector()

  return(list(batchSize = batch1$image$shape[1],
              imageDataType = imgDT,
              maskDataType = mskDT,
              imageShape=imgDims,
              maskShape=mskDims,
              bndMns = bndMns,
              bandSDs = bndSDs,
              maskCount=freqTble,
              minIndex = minIndex,
              maxIndex = maxIndex
              ))
}
