#' describeBatch
#'
#' Generate summary information for a batch of image chips and masks.
#'
#' The goal of this function is to provide a check of a batch of image chips and associated
#' masks generated by a DataLoader instance using defineSegDataSet(). Summary information includes the batch size
#' (batchSize); image chip data type (imageDataType); mask data type (maskDataType); the shape of each
#' image chip as number of channels, height pixel count, and width pixel count (imageShape); the mask shape
#' (maskShape); image band statistics (imageStats) including mean (mean), median (median), minimum (min),
#' maximum (max), and standard deviation (sd); mask class index statistics (mskStats) including minimum (min)
#' and maximum (max) class indices; and count of pixels in each class in the batch (mskCnts).
#'
#' @param dataLoader Instantiated instance of a DataLoader created using torch::dataloader().
#' @param usedDS TRUE or FALSE. If deep supervision is implemented, this must be set to TRUE.
#' Default is FALSE. Whether or not deep supervision was used, only metrics for the masks
#' at the original spatial resolution are returned.
#' @return List object summarizing a batch of image chips and masks.
#' @export
describeBatch <- function(dataLoader, usedDS=FALSE){

  batch1 <- dataLoader$.iter()$.next()

  if(usedDS==TRUE){
    imgDims <- batch1$image[1][1]$shape %>% as.character()
    mskDims <- batch1$mask[1][1]$shape %>% as.character()
    imgDT <- batch1$image[1][1]$dtype %>% as.character()
    mskDT <- batch1$mask[1][1]$dtype %>% as.character()
    batchI <- batch1$image[1] %>% as.array()
    batchM <- batch1$mask[1] %>% as.array()
  }else{
    imgDims <- batch1$image$shape %>% as.character()
    mskDims <- batch1$mask$shape %>% as.character()
    imgDT <- batch1$image[1]$dtype %>% as.character()
    mskDT <- batch1$mask[1]$dtype %>% as.character()
    batchI <- batch1$image[1] %>% as.array()
    batchM <- batch1$mask[1] %>% as.array()
  }

  maskDims <- dim(batchM)

  imgStats <- apply(batchI, 2, function(x) c(mean = mean(x), median=median(x), min = min(x), max = max(x), sd=sd(x)))
  mskStats <- apply(batchM, 2, function(x) c( min = min(x), max = max(x)))

  mskCnts <- table(batchM)

  return(list(batchSize = imgDims[1],
              imageDataType = imgDT,
              maskDataType = mskDT,
              imageShape=imgDims[2:4],
              maskShape=mskDims[2:length(maskDims)],
              imageStats= imgStats,
              maskStats=mskStats,
              maskCount=mskCnts
              ))
}
